### ISSUE TITLE
Giving OS error even after setting ec_sys write_support=1 on Msi P 14 A10RB

### ISSUE THREAD

**Issue by c0dysharma** [YoyPa/isw#110]
I am using Msi Prestige 14 A10RB and trying to apply [this](https://wiki.archlinux.org/index.php/MSI_P14#Fan) config.
I did instructions provided in Builtin or not builtin section. Grub update returned with a error ec_sys_write_support=1 commad not found files was already there on /etc/mod[..] as I used AUR.
$uname -r

5.4.50-1-lts

$modprobe ec_sys write_support=1
$sudo isw -w E14C2IMS                         

Writing config to EC...
Value       set @ address        Fan mode
0x8c(140)   0xf4(byte244)        Advanced

Traceback (most recent call last):
  File "/usr/bin/isw", line 323, in ec_write
    file.seek(list_cta[i])
OSError: [Errno 22] Invalid argument

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/isw", line 427, in <module>
    main()
  File "/usr/bin/isw", line 424, in main
    parser.parse_args()
  File "/usr/lib/python3.8/argparse.py", line 1768, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/lib/python3.8/argparse.py", line 1800, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib/python3.8/argparse.py", line 2006, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/usr/lib/python3.8/argparse.py", line 1946, in consume_optional
    take_action(action, args, option_string)
  File "/usr/lib/python3.8/argparse.py", line 1858, in take_action
    argument_values = self._get_values(action, argument_strings)
  File "/usr/lib/python3.8/argparse.py", line 2389, in _get_values
    value = self._get_value(action, arg_string)
  File "/usr/lib/python3.8/argparse.py", line 2422, in _get_value
    result = type_func(arg_string)
  File "/usr/bin/isw", line 346, in ec_write
    print(Text.FOUR_COLUMN %(
OSError: [Errno 22] Invalid argument

$cat /sys/module/ec_sys/parameters/write_support

N

**Comment by c0dysharma** [comment]
I haven't read wiki properly. MY bad closing issue
