### ISSUE TITLE
MSI GL63-9SDK EC DUMP

### ISSUE THREAD

**Issue by naterz1204** [YoyPa/isw#111]
Thanks for your work!! 

EC dump 
       00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F
000000 00 80 00 00 00 00 00 00 00 00 00 00 00 00 00 00  >................<
000010 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  >................<
000020 00 00 00 00 00 00 00 00 00 00 00 80 c0 06 4a 0b  >..............J.<
000030 03 01 00 05 51 2d 05 00 26 13 6c 2a ea 01 c7 00  >....Q-..&.l*....<
000040 22 0b 51 00 e4 0f 00 00 b7 0c 19 2d bb 0b 0c 30  >".Q........-...0<
000050 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  >................<
000060 00 00 00 00 00 00 00 00 2c 0a 32 38 3e 46 4b 50  >........,.28>FKP<
000070 64 00 00 28 30 38 42 4c 56 00 0a 07 07 09 09 09  >d..(08BLV.......<
000080 29 36 37 3c 41 46 4b 50 61 00 00 2d 36 3e 46 4e  >)67<AFKPa..-6>FN<
000090 4e 00 0a 07 07 07 07 07 02 16 7d 02 16 61 00 00  >N.........}..a..<
0000a0 31 36 50 37 45 4d 53 31 2e 31 30 38 30 34 af 32  >16P7EMS1.10804.2<
0000b0 32 30 31 39 31 34 3a 35 34 3a 30 37 e4 0f 00 00  >201914:54:07....<
0000c0 00 07 25 00 00 9e c0 00 00 0e 00 00 00 00 14 00  >..%.............<
0000d0 00 00 20 00 70 00 00 00 00 00 00 80 00 14 07 12  >.. .p...........<
0000e0 e2 02 00 27 10 00 00 00 00 00 82 00 00 c0 00 d0  >...'............<
0000f0 00 00 80 02 00 00 05 80 00 00 00 00 00 00 00 00  >................<
000100

Profile dump 
Value       set @ address        Fan mode
0x0(0)      0xf4(byte244)        Unknown

-----------CPU-----------        -----------GPU-----------
Value       set @ address        Value       set @ address
0x32(50°C)  0x6a(byte106)        0x37(55°C)  0x82(byte130)
0x38(56°C)  0x6b(byte107)        0x3c(60°C)  0x83(byte131)
0x3e(62°C)  0x6c(byte108)        0x41(65°C)  0x84(byte132)
0x46(70°C)  0x6d(byte109)        0x46(70°C)  0x85(byte133)
0x4b(75°C)  0x6e(byte110)        0x4b(75°C)  0x86(byte134)
0x50(80°C)  0x6f(byte111)        0x50(80°C)  0x87(byte135)

0x0(0%)     0x72(byte114)        0x0(0%)     0x8a(byte138)
0x28(40%)   0x73(byte115)        0x2d(45%)   0x8b(byte139)
0x30(48%)   0x74(byte116)        0x36(54%)   0x8c(byte140)
0x38(56%)   0x75(byte117)        0x3e(62%)   0x8d(byte141)
0x42(66%)   0x76(byte118)        0x46(70%)   0x8e(byte142)
0x4c(76%)   0x77(byte119)        0x4e(78%)   0x8f(byte143)
0x56(86%)   0x78(byte120)        0x4e(78%)   0x90(byte144)

**Comment by naterz1204** [comment]
It appears I'm having issues having isw do anything but read values.. I believe I have enabled EC Write so I'm a bit stumped as to what this error is getting at..

sudo isw -w 16P6EMS1                                                                                                                                            [1]

Writing config to EC...
Value       set @ address        Fan mode
0x8c(140)   0xf4(byte244)        Advanced

Traceback (most recent call last):
  File "/usr/bin/isw", line 323, in ec_write
    file.seek(list_cta[i])
OSError: [Errno 22] Invalid argument

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/isw", line 427, in <module>
    main()
  File "/usr/bin/isw", line 424, in main
    parser.parse_args()
  File "/usr/lib/python3.8/argparse.py", line 1768, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/lib/python3.8/argparse.py", line 1800, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib/python3.8/argparse.py", line 2006, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/usr/lib/python3.8/argparse.py", line 1946, in consume_optional
    take_action(action, args, option_string)
  File "/usr/lib/python3.8/argparse.py", line 1858, in take_action
    argument_values = self._get_values(action, argument_strings)
  File "/usr/lib/python3.8/argparse.py", line 2389, in _get_values
    value = self._get_value(action, arg_string)
  File "/usr/lib/python3.8/argparse.py", line 2422, in _get_value
    result = type_func(arg_string)
  File "/usr/bin/isw", line 346, in ec_write
    print(Text.FOUR_COLUMN %(
OSError: [Errno 22] Invalid argument
