### ISSUE TITLE
isw@16S3EMS1.service OSError: [Errno 22] Invalid argument

### ISSUE THREAD

**Issue by Laestry** [YoyPa/isw#122]
so I"m using the git version and ISW service wont start
● isw@16S3EMS1.service - ISW fan control service
     Loaded: loaded (/usr/lib/systemd/system/isw@.service; enabled; vendor preset: disable>
     Active: failed (Result: exit-code) since Mon 2020-08-31 18:58:12 MSK; 16s ago
    Process: 2803 ExecStartPre=/usr/bin/sleep 2 (code=exited, status=0/SUCCESS)
    Process: 2810 ExecStart=/usr/bin/isw -w 16S3EMS1 (code=exited, status=1/FAILURE)
   Main PID: 2810 (code=exited, status=1/FAILURE)

авг 31 18:58:12 msip15 isw[2810]:   File "/usr/lib/python3.8/argparse.py", line 2389, in _>
авг 31 18:58:12 msip15 isw[2810]:     value = self._get_value(action, arg_string)
авг 31 18:58:12 msip15 isw[2810]:   File "/usr/lib/python3.8/argparse.py", line 2422, in _>
авг 31 18:58:12 msip15 isw[2810]:     result = type_func(arg_string)
авг 31 18:58:12 msip15 isw[2810]:   File "/usr/bin/isw", line 391, in ec_write
авг 31 18:58:12 msip15 isw[2810]:     print(Text.FOUR_COLUMN %(
авг 31 18:58:12 msip15 isw[2810]: OSError: [Errno 22] Invalid argument
авг 31 18:58:12 msip15 systemd[1]: isw@16S3EMS1.service: Main process exited, code=exited,>
авг 31 18:58:12 msip15 systemd[1]: isw@16S3EMS1.service: Failed with result 'exit-code'.
авг 31 18:58:12 msip15 systemd[1]: Failed to start ISW fan control service.

also I tried this

[laestry@msip15 ~]$ sudo isw -w 16J9EMS1
[sudo] password for laestry: 

Writing config to EC...
Value       set @ address        Fan mode
0x8c(140)   0xf4(byte244)        Advanced

Traceback (most recent call last):
  File "/usr/bin/isw", line 356, in ec_write
    file.seek(bcta)
OSError: [Errno 22] Invalid argument

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/isw", line 499, in <module>
    main()
  File "/usr/bin/isw", line 496, in main
    parser.parse_args()
  File "/usr/lib/python3.8/argparse.py", line 1768, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/lib/python3.8/argparse.py", line 1800, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib/python3.8/argparse.py", line 2006, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/usr/lib/python3.8/argparse.py", line 1946, in consume_optional
    take_action(action, args, option_string)
  File "/usr/lib/python3.8/argparse.py", line 1858, in take_action
    argument_values = self._get_values(action, argument_strings)
  File "/usr/lib/python3.8/argparse.py", line 2389, in _get_values
    value = self._get_value(action, arg_string)
  File "/usr/lib/python3.8/argparse.py", line 2422, in _get_value
    result = type_func(arg_string)
  File "/usr/bin/isw", line 391, in ec_write
    print(Text.FOUR_COLUMN %(
OSError: [Errno 22] Invalid argument

**Comment by Laestry** [comment]
cronie.service                                                                         loaded active running   Periodic Command Scheduler                                                  >
  dbus.service                                                                           loaded active running   D-Bus System Message Bus                                                    >
  haveged.service                                                                        loaded active running   Entropy Daemon based on the HAVEGE algorithm                                >
● isw@16S3EMS1.service                                                                   loaded failed failed    ISW fan control service                                                     >
  kmod-static-nodes.service                                                              loaded active exited    Create list of static device nodes for the current kernel                   >
  lightdm.service                                                                        loaded active running   Light Display Manager                                                       >
  lm_sensors.service                                                                     loaded active exited    Initialize hardware monitoring sensors                                      >
  lvm2-lvmetad.service                                                                   loaded active running   LVM2 metadata daemon                                                        >
  lvm2-monitor.service                                                                   loaded active exited    Monitoring of LVM2 mirrors, snapshots etc. using dmeventd or progress pollin>
  ModemManager.service                                                                   loaded active running   Modem Manager

**Comment by Laestry** [comment]
right I figured out what I needed to do. Just new to linux and didn't understand how that I needed to edit the grub file and how to do it
if anyone struggles here it is, just add this to it and it should work:
RUB_CMDLINE_LINUX_DEFAULT="quiet ec_sys.write_support=1"
https://github.com/YoyPa/isw/wiki/How-to-configure-ec_sys-with-write_support=1
