### ISSUE TITLE
MSI GF63_8RC unable to write EC

### ISSUE THREAD

**Issue by piyush-bajaj** [YoyPa/isw#196]
Since i don't have a battery in my laptop, unable to write the EC config, failing in python code line 356 "file.seek(bcta)".
After printing the value of bcta i get the value as 239 and for bct the value is 100.

Below is the error:
sudo isw -w 16R1EMS1

Writing config to EC...
Value       set @ address        Fan mode
0x8c(140)   0xf4(byte244)        Advanced

Traceback (most recent call last):
  File "/usr/bin/isw", line 356, in ec_write
    file.seek(bcta)
OSError: [Errno 22] Invalid argument

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/isw", line 499, in <module>
    main()
  File "/usr/bin/isw", line 496, in main
    parser.parse_args()
  File "/usr/lib/python3.8/argparse.py", line 1780, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/lib/python3.8/argparse.py", line 1812, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib/python3.8/argparse.py", line 2018, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/usr/lib/python3.8/argparse.py", line 1958, in consume_optional
    take_action(action, args, option_string)
  File "/usr/lib/python3.8/argparse.py", line 1870, in take_action
    argument_values = self._get_values(action, argument_strings)
  File "/usr/lib/python3.8/argparse.py", line 2401, in _get_values
    value = self._get_value(action, arg_string)
  File "/usr/lib/python3.8/argparse.py", line 2434, in _get_value
    result = type_func(arg_string)
  File "/usr/bin/isw", line 391, in ec_write
    print(Text.FOUR_COLUMN %(
OSError: [Errno 22] Invalid argument

The profile dump is as below:

$ sudo isw -cp 16R1EMS1

EC dump 
       00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F
000000 00 80 00 00 00 00 00 00 00 00 00 00 00 00 00 00  >................<
000010 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  >................<
000020 00 00 00 00 00 00 00 00 00 01 00 80 c0 06 48 0b  >..............H.<
000030 03 00 00 0d 50 0a 05 00 00 00 00 00 00 00 00 00  >....P...........<
000040 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  >................<
*
000060 00 00 00 00 00 00 00 00 33 00 37 40 49 4c 52 58  >........3.7@ILRX<
000070 64 26 23 26 2a 2d 32 37 3e 00 08 03 03 03 03 03  >d&#&*-27>.......<
000080 33 00 37 3d 43 49 4f 55 63 23 23 26 2a 2d 32 37  >3.7=CIOUc##&*-27<
000090 3e 00 08 03 03 03 03 03 02 00 64 02 00 6e 00 00  >>.........d..n..<
0000a0 31 36 52 31 45 4d 53 31 2e 31 30 33 30 36 30 35  >16R1EMS1.1030605<
0000b0 32 30 31 38 30 38 3a 35 33 3a 31 31 00 00 00 40  >201808:53:11...@<
0000c0 00 01 25 00 00 00 00 00 00 50 00 00 00 e5 14 00  >..%......P......<
0000d0 00 00 10 00 7f 00 d1 00 00 00 00 80 00 00 00 00  >................<
0000e0 e2 02 00 08 10 00 00 00 00 00 00 00 00 d1 00 00  >................<
0000f0 00 00 80 00 0c 00 05 00 00 00 00 00 00 00 00 00  >................<
000100

Profile dump 
Value       set @ address        Fan mode
0xc(12)     0xf4(byte244)        Auto

Value       set @ address        Charging below - stop @
0x0(0)      0xef(byte239)        Nothing is set

-----------CPU-----------        -----------GPU-----------
Value       set @ address        Value       set @ address
0x37(55°C)  0x6a(byte106)        0x37(55°C)  0x82(byte130)
0x40(64°C)  0x6b(byte107)        0x3d(61°C)  0x83(byte131)
0x49(73°C)  0x6c(byte108)        0x43(67°C)  0x84(byte132)
0x4c(76°C)  0x6d(byte109)        0x49(73°C)  0x85(byte133)
0x52(82°C)  0x6e(byte110)        0x4f(79°C)  0x86(byte134)
0x58(88°C)  0x6f(byte111)        0x55(85°C)  0x87(byte135)

0x23(35%)   0x72(byte114)        0x23(35%)   0x8a(byte138)
0x26(38%)   0x73(byte115)        0x26(38%)   0x8b(byte139)
0x2a(42%)   0x74(byte116)        0x2a(42%)   0x8c(byte140)
0x2d(45%)   0x75(byte117)        0x2d(45%)   0x8d(byte141)
0x32(50%)   0x76(byte118)        0x32(50%)   0x8e(byte142)
0x37(55%)   0x77(byte119)        0x37(55%)   0x8f(byte143)
0x3e(62%)   0x78(byte120)        0x3e(62%)   0x90(byte144)

**Comment by piyush-bajaj** [comment]
It works fine, for me i had to reboot multiple times for the effects to take place.
