### ISSUE TITLE
MSI Modern 15 B12HW-002XRU

### ISSUE THREAD

**Issue by XeemPad** [YoyPa/isw#278]
Output of the **sudo isw -cp MSI_ADDRESS_DEFAULT**:
```
EC dump 
       00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F
od: /sys/kernel/debug/ec/ec0/io: No such file or directory

Profile dump 
Traceback (most recent call last):
  File "/usr/bin/isw", line 427, in <module>
    main()
  File "/usr/bin/isw", line 424, in main
    parser.parse_args()
  File "/usr/lib/python3.11/argparse.py", line 1869, in parse_args
    args, argv = self.parse_known_args(args, namespace)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/argparse.py", line 1902, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/argparse.py", line 2114, in _parse_known_args
    start_index = consume_optional(start_index)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/argparse.py", line 2054, in consume_optional
    take_action(action, args, option_string)
  File "/usr/lib/python3.11/argparse.py", line 1962, in take_action
    argument_values = self._get_values(action, argument_strings)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/argparse.py", line 2496, in _get_values
    value = self._get_value(action, arg_string)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/argparse.py", line 2529, in _get_value
    result = type_func(arg_string)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/isw", line 151, in ec_profile
    with open(EC_IO_FILE,'r+b') as file:
         ^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/sys/kernel/debug/ec/ec0/io'
```

**Comment by XeemPad** [comment]
UPDATE:

I used a `sudo modprobe ec_sys`, then the `sudo isw -cp MSI_ADDRESS_DEFAULT` actually worked:

```
EC dump 
       00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F
000000 00 80 00 00 00 00 00 00 00 00 00 00 00 00 00 00  >................<
000010 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  >................<
000020 00 00 00 00 00 00 00 00 0a 05 00 00 00 08 0b 0a  >................<
000030 03 01 00 05 00 00 50 81 f8 11 88 2c cc 01 c0 00  >......P....,....<
000040 f8 11 33 00 f9 0f 00 00 09 08 ff 2c c3 0b fa 32  >..3........,...2<
000050 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  >................<
000060 00 00 00 00 00 00 00 00 3b 00 3c 41 46 50 52 58  >........;.<AFPRX<
000070 64 00 00 37 41 46 4b 50 50 00 03 03 03 03 03 03  >d..7AFKPP.......<
000080 39 00 3c 41 46 50 52 58 00 00 00 37 41 46 4b 50  >9.<AFPRX...7AFKP<
000090 50 64 03 03 03 03 03 03 02 00 00 04 00 00 00 00  >Pd..............<
0000a0 31 35 48 32 49 4d 53 31 2e 31 30 35 30 37 31 39  >15H2IMS1.1050719<
0000b0 32 30 32 32 31 34 3a 30 36 3a 34 30 00 00 00 28  >202214:06:40...(<
0000c0 00 00 06 22 00 00 00 00 00 00 00 00 00 00 00 00  >..."............<
0000d0 00 00 c1 80 0d 00 05 bc 00 02 00 00 00 04 00 00  >................<
0000e0 e2 00 00 f9 0f 01 00 00 01 00 00 00 00 c5 00 00  >................<
0000f0 00 00 70 00 36 3c 32 3c 3c 32 00 00 00 00 00 00  >..p.6<2<<2......<
000100

Profile dump 
Value       set @ address        Fan mode
0x36(54)    0xf4(byte244)        Unknown








-----------CPU-----------        -----------GPU-----------
Value       set @ address        Value       set @ address
0x3c(60°C)  0x6a(byte106)        0x3c(60°C)  0x82(byte130)
0x41(65°C)  0x6b(byte107)        0x41(65°C)  0x83(byte131)
0x46(70°C)  0x6c(byte108)        0x46(70°C)  0x84(byte132)
0x50(80°C)  0x6d(byte109)        0x50(80°C)  0x85(byte133)
0x52(82°C)  0x6e(byte110)        0x52(82°C)  0x86(byte134)
0x58(88°C)  0x6f(byte111)        0x58(88°C)  0x87(byte135)

0x0(0%)     0x72(byte114)        0x0(0%)     0x8a(byte138)
0x37(55%)   0x73(byte115)        0x37(55%)   0x8b(byte139)
0x41(65%)   0x74(byte116)        0x41(65%)   0x8c(byte140)
0x46(70%)   0x75(byte117)        0x46(70%)   0x8d(byte141)
0x4b(75%)   0x76(byte118)        0x4b(75%)   0x8e(byte142)
0x50(80%)   0x77(byte119)        0x50(80%)   0x8f(byte143)
0x50(80%)   0x78(byte120)        0x50(80%)   0x90(byte144)

```
